spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ccnu_app_demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  type-aliases-package: com.edu.ccnu.app.demo.pojo
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8088
  session-timeout: 1800
  servlet:
    context-path: /schoolsystem
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8
    basedir: target/tomcat
